apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: blog
  labels:
    app: blog
type: Opaque
data:
  root-password: <base64_encoded_password>
  user-password: <base64_encoded_password>

