apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  - name: nginx-logs
    hostPath:
      path: /var/log/nginx
      type: DirectoryOrCreate
  initContainers:
  - name: init-fetch
    image: curlimages/curl:latest
    command: ['sh', '-c', 'curl http://example.com/index.html -o /usr/share/nginx/html/index.html']
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    - name: nginx-logs
      mountPath: /var/log/nginx
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10

